name: Rust

permissions:
  contents: read
  checks: write

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    name: format
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: install rust
      uses: dtolnay/rust-toolchain@nightly
      with:
        components: rustfmt
    - name: cargo fmt
      run: cargo fmt --check

  clippy:
    name: clippy
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: install openmpi
      run: sudo apt install libopenmpi-dev
    - name: install rust
      uses: dtolnay/rust-toolchain@nightly
      with:
        components: clippy
    - name: cargo clippy
      run: cargo clippy --all-features --tests --examples -- --deny warnings
    
  doc:
    name: doc
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: install openmpi
      run: sudo apt install libopenmpi-dev
    - name: install rust
      uses: dtolnay/rust-toolchain@nightly
    - name: load cache
      uses: Swatinem/rust-cache@v2
    - name: cargo doc
      env:
        RUSTDOCFLAGS: "-D warnings" 
      run: cargo doc --no-deps --all-features

  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: install openmpi
      run: sudo apt install libopenmpi-dev
    - name: install rust
      uses: dtolnay/rust-toolchain@nightly
    - name: load cache
      uses: Swatinem/rust-cache@v2
    - name: cargo build
      run: cargo build --release --tests --examples

  test:
    name: test
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: install openmpi
      run: sudo apt install libopenmpi-dev
    - name: install rust
      uses: dtolnay/rust-toolchain@nightly
    - name: load cache
      uses: Swatinem/rust-cache@v2
    - name: cargo test
      run: cargo test --all-features

  deps:
    name: unused deps
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: load cache
      uses: Swatinem/rust-cache@v2
    - name: install cargo-machete
      run: cargo install cargo-machete
    - name: cargo machete
      run: cargo machete